# Generated by Django 5.0.2 on 2024-03-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
