# Generated by Django 5.0.2 on 2024-03-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_delete_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
