# Generated by Django 5.0.2 on 2024-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_delete_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrealumno', models.CharField(max_length=50)),
                ('numcomision', models.IntegerField()),
                ('turno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrealumno', models.CharField(max_length=50)),
                ('numcomision', models.IntegerField()),
                ('nombreProfesor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='ExamenFinal',
            new_name='Mesa',
        ),
    ]
