# Generated by Django 5.0.2 on 2024-03-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_cursado_examen_rename_examenfinal_mesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='profesorCorrigio',
            new_name='NombreAlumno',
        ),
    ]
