# Generated by Django 5.0.2 on 2024-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_rename_profesorcorrigio_calificacion_nombrealumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='nombreMateria',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
