# Generated by Django 5.0.2 on 2024-03-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_examen_nombremateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificacion', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name': 'Comision', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='cursado',
            options={'verbose_name': 'Cursado', 'verbose_name_plural': 'Cursados'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Examenes'},
        ),
    ]
