# Generated by Django 4.2.5 on 2024-03-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tramite',
        ),
    ]
