# Generated by Django 4.2.5 on 2024-03-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_delete_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMateria', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='modelos')),
            ],
        ),
    ]
